version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: skatego_db
      POSTGRES_USER: skatego_user
      POSTGRES_PASSWORD: skatego_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skatego_user -d skatego_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python skatego/manage.py migrate &&
             python skatego/manage.py collectstatic --noinput &&
             python skatego/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=skatego_db
      - DB_USER=skatego_user
      - DB_PASSWORD=skatego_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-)iv7)t=p-ph%e=lwa-&8bw2(5)n=baj(hw**&q4t!%ssdfy-o#
    restart: unless-stopped

volumes:
  postgres_data:
