# Generated by Django 5.2.3 on 2025-06-24 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkateboardRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала аренды')),
                ('end_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Время завершения аренды')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=10, verbose_name='Статус аренды')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15000.0)], verbose_name='Стоимость аренды')),
                ('distanse_traveled_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)], verbose_name='Длина поездки (km)')),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_end', to='core.skateboardlocation', verbose_name='Конечная локация')),
                ('skateboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='core.skateboard', verbose_name='Скейтборд')),
                ('start_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_start', to='core.skateboardlocation', verbose_name='Начальная локация')),
            ],
        ),
    ]
